[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bonkers = "DYjXGPz5HGneqvA7jsgRVKTTaeoarCPNCH6pr9Lu2L3F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keypairs/BnKRsvhxmjnvpt7kGFLgBUgRT7NL2hJQzmvxSut4Lg5s.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
